---

# Base Docker Compose file.
# This defines the basic environments that are used for both develoment and
# testing. Overrides are explicitly specified in the Makefile for their
# relevant targets.
#
# Many patterns here lifted directly from:
# <https://github.com/wemake-services/wemake-django-template>

services:
    api:
        image: "api_ashes_live:dev"
        build:
            context: .
        # env_file populates environment variables at runtime
        env_file: .env
        restart: unless-stopped
