---

# This docker-compose file is required to bind ports and volumes for local development
# and is automatically loaded when running a docker-compose command without passing
# specific files with the `-f` flag.

version: '3.7'
services:
    postgres:
        image: postgres:11
        restart: unless-stopped
        networks:
            - localnet
        env_file: .env
        ports:
            # Adding 127.0.0.1 ensures that we only listen to local requests
            - '127.0.0.1:5432:5432'
        volumes:
            - pgdata:/var/lib/postgresql/data

    api:
        build:
            target: development_build
            args:
                ENV: local
        init: true
        depends_on:
            - postgres
        networks:
            - localnet
        ports:
            # We only bind ports directly in development; need to listen to remote requests to allow local network access
            - '8000:8000'
        volumes:
            # We only mount source code in development:
            - .:/code
        command: python -m uvicorn api:app --reload --host 0.0.0.0 --port 8000

networks:
    # Network for local internals
    localnet:

volumes:
    pgdata:
