---

# This docker-compose file is required to bind ports and volumes for local development
# and is automatically loaded when running a docker-compose command without passing
# specific files with the `-f` flag.

version: '3.7'
services:
    postgres:
        image: postgres:11.7
        restart: unless-stopped
        networks:
            - localnet
        env_file: .env
        ports:
            - '5432:5432'
        volumes:
            - pgdata:/var/lib/postgresql/data

    api:
        build:
            target: development_build
            args:
                ENV: development
        depends_on:
            - postgres
        networks:
            - localnet
        ports:
            # We only bind ports directly in development:
            - '8000:8000'
        volumes:
            # We only mount source code in development:
            - .:/code
        command: python -m uvicorn api:app --reload --host 0.0.0.0 --port 8000

networks:
    # Network for local internals
    localnet:

volumes:
    pgdata:
