---

# Base Docker Compose file.
# This defines the basic environments that are used for both develoment and
# testing. Overrides are explicitly specified in the Makefile for their
# relevant targets.
#
# Many patterns here lifted directly from:
# <https://github.com/wemake-services/wemake-django-template>

version: '3.7'
services:
    api:
        image: "api_ashes_live:dev"
        build:
            context: .
            dockerfile: ./docker/Dockerfile
            cache_from:
                - "api_ashes_live:dev"
                - "api_ashes_live:latest"
                - "*"
        # env_file populates environment variables at runtime
        env_file: .env
        healthcheck:
            # We use `$$` here because:
            # one `$` goes to shell,
            # one `$` goes to `docker-compose.yml` escaping
            test: |
              /usr/bin/test $$(
                /usr/bin/curl --fail http://localhost:8000/health-check
                --write-out "%{http_code}" --silent --output /dev/null
              ) -eq 200
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 30s
        restart: unless-stopped
